In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"kalpitasingha","key":"96577f12a1d4f75b15121b8787efe777"}'}

In [3]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle datasets download -d sumanbera19/bengaluru-house-price-dataset

Dataset URL: https://www.kaggle.com/datasets/sumanbera19/bengaluru-house-price-dataset
License(s): CC0-1.0
Downloading bengaluru-house-price-dataset.zip to /content
100% 194k/194k [00:00<00:00, 77.9MB/s]

In [5]:
import zipfile

In [6]:
with zipfile.ZipFile("bengaluru-house-price-dataset.zip") as z:
  z.extractall("House")

In [7]:
import numpy as np
import pandas as pd

In [8]:
data=pd.read_csv("/content/House/bengaluru_house_prices.csv")
df=pd.DataFrame(data)
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [10]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [11]:
df.isnull().sum().sum()

np.int64(6201)

In [12]:
df.size

119880

In [13]:
df1_1=df.dropna()
df1_1.size

67464

In [14]:
df_2=df.fillna(100)
df_2.size

119880

In [15]:
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [16]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [17]:
df.shape

(13320, 9)

In [18]:
a=df.isnull().sum()/df.shape[0]*100
a

area_type        0.000000
availability     0.000000
location         0.007508
size             0.120120
society         41.306306
total_sqft       0.000000
bath             0.548048
balcony          4.572072
price            0.000000
dtype: float64

In [19]:
b=a[a>17].keys()
b

Index(['society'], dtype='object')

In [20]:
df.drop(b,axis=1,inplace=True)

In [21]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.00

In [22]:
df.isnull().sum()

area_type         0
availability      0
location          1
size             16
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [23]:
cat_col=df.select_dtypes(include=["object"]).columns.tolist()
cat_col

['area_type', 'availability', 'location', 'size', 'total_sqft']

In [24]:
num_col=df.select_dtypes(include=["int64","float64"]).columns.tolist()
num_col

['bath', 'balcony', 'price']

In [25]:
from sklearn.impute import SimpleImputer

In [26]:
cat_clean=SimpleImputer(strategy="most_frequent")
num_clean=SimpleImputer(strategy="mean")

In [27]:
df[cat_col]=cat_clean.fit_transform(df[cat_col])
df[num_col]=num_clean.fit_transform(df[num_col])

In [28]:
df.isnull().sum().sum()

np.int64(0)

In [29]:
df.size

106560

In [30]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.000000,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.000000,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.000000,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.000000,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.000000,51.00
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.000000,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,1.584376,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.000000,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.000000,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.000000,17.00

In [31]:
df['price']=df['price']*100000
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.000000,3907000.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.000000,12000000.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.000000,6200000.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.000000,9500000.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.000000,5100000.0
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.000000,23100000.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,1.584376,40000000.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.000000,6000000.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.000000,48800000.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.000000,1700000.0

In [32]:
print("2 BHK")

2 BHK

In [33]:
a=df['size'].apply(lambda x:int(x.split(" ")[0]))
a

0        2
1        4
2        3
3        3
4        2
        ..
13315    5
13316    4
13317    2
13318    4
13319    1
Name: size, Length: 13320, dtype: int64

In [34]:
df.insert(3,"BHK",a)

In [35]:
df

,area_type,availability,location,BHK,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,2 BHK,1056,2.0,1.000000,3907000.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4,4 Bedroom,2600,5.0,3.000000,12000000.0
2,Built-up Area,Ready To Move,Uttarahalli,3,3 BHK,1440,2.0,3.000000,6200000.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,3 BHK,1521,3.0,1.000000,9500000.0
4,Super built-up Area,Ready To Move,Kothanur,2,2 BHK,1200,2.0,1.000000,5100000.0
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5,5 Bedroom,3453,4.0,0.000000,23100000.0
13316,Super built-up Area,Ready To Move,Richards Town,4,4 BHK,3600,5.0,1.584376,40000000.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2,2 BHK,1141,2.0,1.000000,6000000.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4,4 BHK,4689,4.0,1.000000,48800000.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1,1 BHK,550,1.0,1.000000,1700000.0

In [36]:
df.drop("size",axis=1,inplace=True)

In [37]:
df

,area_type,availability,location,BHK,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,1056,2.0,1.000000,3907000.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4,2600,5.0,3.000000,12000000.0
2,Built-up Area,Ready To Move,Uttarahalli,3,1440,2.0,3.000000,6200000.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,1521,3.0,1.000000,9500000.0
4,Super built-up Area,Ready To Move,Kothanur,2,1200,2.0,1.000000,5100000.0
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5,3453,4.0,0.000000,23100000.0
13316,Super built-up Area,Ready To Move,Richards Town,4,3600,5.0,1.584376,40000000.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2,1141,2.0,1.000000,6000000.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4,4689,4.0,1.000000,48800000.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1,550,1.0,1.000000,1700000.0

In [38]:
df.drop(["area_type","availability"],axis=1,inplace=True)

In [39]:
df

                       location  BHK total_sqft  bath   balcony       price
0      Electronic City Phase II    2       1056   2.0  1.000000   3907000.0
1              Chikka Tirupathi    4       2600   5.0  3.000000  12000000.0
2                   Uttarahalli    3       1440   2.0  3.000000   6200000.0
3            Lingadheeranahalli    3       1521   3.0  1.000000   9500000.0
4                      Kothanur    2       1200   2.0  1.000000   5100000.0
...                         ...  ...        ...   ...       ...         ...
13315                Whitefield    5       3453   4.0  0.000000  23100000.0
13316             Richards Town    4       3600   5.0  1.584376  40000000.0
13317     Raja Rajeshwari Nagar    2       1141   2.0  1.000000   6000000.0
13318           Padmanabhanagar    4       4689   4.0  1.000000  48800000.0
13319              Doddathoguru    1        550   1.0  1.000000   1700000.0

[13320 rows x 6 columns]

In [41]:
# df.insert(5,"price/sqft",df["price"]/df['total_sqft'])

In [42]:
df["price"].dtypes

dtype('float64')

In [43]:
df['total_sqft'].dtypes

dtype('O')

In [44]:
def check(x):
  try:
   float(x)
   return True
  except:
    return False

In [45]:
z=df[~df['total_sqft'].apply(check)]

In [46]:
z

                 location  BHK   total_sqft     bath   balcony       price
30              Yelahanka    4  2100 - 2850  4.00000  0.000000  18600000.0
56            Devanahalli    4  3010 - 3410  2.69261  1.584376  19200000.0
81            Hennur Road    4  2957 - 3450  2.69261  1.584376  22450000.0
122                Hebbal    4  3067 - 8156  4.00000  0.000000  47700000.0
137    8th Phase JP Nagar    2  1042 - 1105  2.00000  0.000000   5400500.0
...                   ...  ...          ...      ...       ...         ...
12990      Talaghattapura    3  1804 - 2273  3.00000  0.000000  12200000.0
13059              Harlur    2  1200 - 1470  2.00000  0.000000   7276000.0
13240         Devanahalli    1  1020 - 1130  2.69261  1.584376   5257000.0
13265               Hoodi    2  1133 - 1384  2.00000  0.000000   5913500.0
13299          Whitefield    4  2830 - 2882  5.00000  0.000000  15450000.0

[247 rows x 6 columns]

In [47]:
def convert(x):
  if isinstance(x,str):
    x=x.strip()
    if "-" in x:
      try:
        a,b=x.split("-")
        return (float(a)+float(b))/2
      except:
        return float(x)
    try:
      return float(x)
    except:
      return np.nan
  return np.nan

In [48]:
df['total_sqft']=df['total_sqft'].apply(convert)

In [49]:
df.shape

(13320, 6)

In [50]:
df.isnull().sum()

location       0
BHK            0
total_sqft    46
bath           0
balcony        0
price          0
dtype: int64

In [51]:
df_1=df.dropna(inplace=True)

In [52]:
df_1

In [53]:
df_1

In [54]:
df

                       location  BHK  total_sqft  bath   balcony       price
0      Electronic City Phase II    2      1056.0   2.0  1.000000   3907000.0
1              Chikka Tirupathi    4      2600.0   5.0  3.000000  12000000.0
2                   Uttarahalli    3      1440.0   2.0  3.000000   6200000.0
3            Lingadheeranahalli    3      1521.0   3.0  1.000000   9500000.0
4                      Kothanur    2      1200.0   2.0  1.000000   5100000.0
...                         ...  ...         ...   ...       ...         ...
13315                Whitefield    5      3453.0   4.0  0.000000  23100000.0
13316             Richards Town    4      3600.0   5.0  1.584376  40000000.0
13317     Raja Rajeshwari Nagar    2      1141.0   2.0  1.000000   6000000.0
13318           Padmanabhanagar    4      4689.0   4.0  1.000000  48800000.0
13319              Doddathoguru    1       550.0   1.0  1.000000   1700000.0

[13274 rows x 6 columns]

In [55]:
df_2=df.dropna(subset=["total_sqft"],inplace=True)

In [56]:
df_2

In [57]:
df_2

In [58]:
df.insert(5,"price/sqft",df["price"]/df['total_sqft'])

In [59]:
df

,location,BHK,total_sqft,bath,balcony,price/sqft,price
0,Electronic City Phase II,2,1056.0,2.0,1.000000,3699.810606,3907000.0
1,Chikka Tirupathi,4,2600.0,5.0,3.000000,4615.384615,12000000.0
2,Uttarahalli,3,1440.0,2.0,3.000000,4305.555556,6200000.0
3,Lingadheeranahalli,3,1521.0,3.0,1.000000,6245.890861,9500000.0
4,Kothanur,2,1200.0,2.0,1.000000,4250.000000,5100000.0
...,...,...,...,...,...,...,...
13315,Whitefield,5,3453.0,4.0,0.000000,6689.834926,23100000.0
13316,Richards Town,4,3600.0,5.0,1.584376,11111.111111,40000000.0
13317,Raja Rajeshwari Nagar,2,1141.0,2.0,1.000000,5258.545136,6000000.0
13318,Padmanabhanagar,4,4689.0,4.0,1.000000,10407.336319,48800000.0
13319,Doddathoguru,1,550.0,1.0,1.000000,3090.909091,1700000.0