In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"kalpitasingha","key":"96577f12a1d4f75b15121b8787efe777"}'}

In [8]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [9]:
!kaggle datasets download -d sumanbera19/bengaluru-house-price-dataset

Dataset URL: https://www.kaggle.com/datasets/sumanbera19/bengaluru-house-price-dataset
License(s): CC0-1.0
Downloading bengaluru-house-price-dataset.zip to /content
100% 194k/194k [00:00<00:00, 68.5MB/s]

In [3]:
import zipfile

In [14]:
with zipfile.ZipFile("bengaluru-house-price-dataset.zip") as z:
  z.extractall("House")

In [12]:
import numpy as np
import pandas as pd

In [10]:
import pandas as pd
data=pd.read_csv("/content/House/Bengaluru_House_Data.csv")
df=pd.DataFrame(data)
df

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

In [21]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/118LzPneQeirs1cCsBnKcES9aLl02aV9uoqeDRraPQ_s/edit#gid=0

In [20]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [19]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [22]:
df.size

119880

In [24]:
df1_1=df.dropna()
df1_1.size

67464

In [25]:
df_2=df.fillna(100)
df_2.size

119880

In [27]:
df.shape

(13320, 9)

In [38]:
a=df.isnull().sum()/df.shape[0]*100
a

area_type        0.000000
availability     0.000000
location         0.007508
size             0.120120
society         41.306306
total_sqft       0.000000
bath             0.548048
balcony          4.572072
price            0.000000
dtype: float64

In [12]:
a=df.isnull().sum()/df.shape[0]*100
b=a[a>17].keys()
b

Index(['society'], dtype='object')

In [39]:
print("Current columns in df:")
print(df.columns)

if 'society' in df.columns:
  print("The 'society' column is still present in the DataFrame. Attempting to drop it now.")
  # Re-calculate 'b' if needed, though in this case, we know it's 'society'
  # a = df.isnull().sum()/df.shape[0]*100
  # b = a[a > 17].keys()
  df.drop('society', axis=1, inplace=True)
  print("The 'society' column has been dropped.")
else:
  print("The 'society' column is not found in the DataFrame (it has likely already been dropped).")

Current columns in df:
Index(['area_type', 'availability', 'location', 'size', 'total_sqft', 'bath',
       'balcony', 'price'],
      dtype='object')
The 'society' column is not found in the DataFrame (it has likely already been dropped).

In [16]:
print(df.columns)

Index(['area_type', 'availability', 'location', 'size', 'total_sqft', 'bath',
       'balcony', 'price'],
      dtype='object')

In [25]:
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.000000,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.000000,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.000000,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.000000,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.000000,51.00
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.000000,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,1.584376,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.000000,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.000000,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.000000,17.00

In [36]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [42]:
import time

In [31]:
import numpy as np
import time

a=np.arange(100000000)
start=time.time()
for i in range(len(a)): # Iterate over indices instead of values
  a[i]+=10
end=time.time()
rt=end-start
print(f"Time taken for loop: {rt} seconds")

Time taken for loop: 63.69855737686157 seconds

In [46]:
a=np.arange(100000000)
start=time.time()
b=a+10
end=time.time()
rt=end-start
rt

0.6054666042327881

In [20]:
cat_col=df.select_dtypes(include=["object"]).columns.tolist()
cat_col

['area_type', 'availability', 'location', 'size', 'total_sqft']

In [21]:
num_col=df.select_dtypes(include=["int64","float64"]).columns.tolist()
num_col

['bath', 'balcony', 'price']

In [22]:
from sklearn.impute import SimpleImputer

In [23]:
cat_clean=SimpleImputer(strategy="most_frequent")
num_clean=SimpleImputer(strategy="mean")

In [24]:
df[cat_col]=cat_clean.fit_transform(df[cat_col])
df[num_col]=num_clean.fit_transform(df[num_col])

In [28]:
df.isnull().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [29]:
df['price']=df['price']*100000000
df

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.000000,3.907000e+09
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.000000,1.200000e+10
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.000000,6.200000e+09
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.000000,9.500000e+09
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.000000,5.100000e+09
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.000000,2.310000e+10
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,3600,5.0,1.584376,4.000000e+10
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.000000,6.000000e+09
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.000000,4.880000e+10
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.000000,1.700000e+09

In [32]:
print("2 BHK")

2 BHK

In [38]:
a=df['size'].apply(lambda x:int(x.split(" ")[0]))
a

0        2
1        4
2        3
3        3
4        2
        ..
13315    5
13316    4
13317    2
13318    4
13319    1
Name: size, Length: 13320, dtype: int64

In [41]:
df.insert(3,"BHK",a)
df

,area_type,availability,location,BHK,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,2 BHK,1056,2.0,1.000000,3.907000e+09
1,Plot Area,Ready To Move,Chikka Tirupathi,4,4 Bedroom,2600,5.0,3.000000,1.200000e+10
2,Built-up Area,Ready To Move,Uttarahalli,3,3 BHK,1440,2.0,3.000000,6.200000e+09
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,3 BHK,1521,3.0,1.000000,9.500000e+09
4,Super built-up Area,Ready To Move,Kothanur,2,2 BHK,1200,2.0,1.000000,5.100000e+09
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5,5 Bedroom,3453,4.0,0.000000,2.310000e+10
13316,Super built-up Area,Ready To Move,Richards Town,4,4 BHK,3600,5.0,1.584376,4.000000e+10
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2,2 BHK,1141,2.0,1.000000,6.000000e+09
13318,Super built-up Area,18-Jun,Padmanabhanagar,4,4 BHK,4689,4.0,1.000000,4.880000e+10
13319,Super built-up Area,Ready To Move,Doddathoguru,1,1 BHK,550,1.0,1.000000,1.700000e+09

In [43]:
df.drop("size",axis=1,inplace=True)

In [44]:
df

,area_type,availability,location,BHK,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,1056,2.0,1.000000,3.907000e+09
1,Plot Area,Ready To Move,Chikka Tirupathi,4,2600,5.0,3.000000,1.200000e+10
2,Built-up Area,Ready To Move,Uttarahalli,3,1440,2.0,3.000000,6.200000e+09
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,1521,3.0,1.000000,9.500000e+09
4,Super built-up Area,Ready To Move,Kothanur,2,1200,2.0,1.000000,5.100000e+09
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5,3453,4.0,0.000000,2.310000e+10
13316,Super built-up Area,Ready To Move,Richards Town,4,3600,5.0,1.584376,4.000000e+10
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2,1141,2.0,1.000000,6.000000e+09
13318,Super built-up Area,18-Jun,Padmanabhanagar,4,4689,4.0,1.000000,4.880000e+10
13319,Super built-up Area,Ready To Move,Doddathoguru,1,550,1.0,1.000000,1.700000e+09

In [55]:
df.insert(5,"price/sqft",(df["price"]*100000)/df["total_sqft"])

In [49]:
import numpy as np

def convert(x):
    if isinstance(x, str):
        x = x.strip()
        if "-" in x:
            try:
                a, b = x.split("-") # Corrected typo: used parentheses for .split()
                return (float(a) + float(b)) / 2
            except ValueError: # Corrected indentation, added specific exception
                return np.nan
        else: # Corrected indentation for else branch
            try:
                return float(x)
            except ValueError:
                return np.nan
    else: # Corrected indentation for else branch
        try:
            return float(x)
        except ValueError:
            return np.nan
    return np.nan # Corrected indentation

In [54]:
df['total_sqft']=df['total_sqft'].apply(convert)
df.dropna(inplace=True)

In [53]:
df

,area_type,availability,location,BHK,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,1056,2.0,1.000000,3.907000e+09
1,Plot Area,Ready To Move,Chikka Tirupathi,4,2600,5.0,3.000000,1.200000e+10
2,Built-up Area,Ready To Move,Uttarahalli,3,1440,2.0,3.000000,6.200000e+09
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,1521,3.0,1.000000,9.500000e+09
4,Super built-up Area,Ready To Move,Kothanur,2,1200,2.0,1.000000,5.100000e+09
...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5,3453,4.0,0.000000,2.310000e+10
13316,Super built-up Area,Ready To Move,Richards Town,4,3600,5.0,1.584376,4.000000e+10
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2,1141,2.0,1.000000,6.000000e+09
13318,Super built-up Area,18-Jun,Padmanabhanagar,4,4689,4.0,1.000000,4.880000e+10
13319,Super built-up Area,Ready To Move,Doddathoguru,1,550,1.0,1.000000,1.700000e+09

In [61]:
df_2 = df.dropna(subset=["total_sqft"]) # Corrected typos and removed inplace=True to ensure df_2 is a DataFrame

In [62]:
df_2

,area_type,availability,location,BHK,total_sqft,price/sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,1056.0,3.699811e+11,2.0,1.000000,3.907000e+09
1,Plot Area,Ready To Move,Chikka Tirupathi,4,2600.0,4.615385e+11,5.0,3.000000,1.200000e+10
2,Built-up Area,Ready To Move,Uttarahalli,3,1440.0,4.305556e+11,2.0,3.000000,6.200000e+09
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,1521.0,6.245891e+11,3.0,1.000000,9.500000e+09
4,Super built-up Area,Ready To Move,Kothanur,2,1200.0,4.250000e+11,2.0,1.000000,5.100000e+09
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5,3453.0,6.689835e+11,4.0,0.000000,2.310000e+10
13316,Super built-up Area,Ready To Move,Richards Town,4,3600.0,1.111111e+12,5.0,1.584376,4.000000e+10
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2,1141.0,5.258545e+11,2.0,1.000000,6.000000e+09
13318,Super built-up Area,18-Jun,Padmanabhanagar,4,4689.0,1.040734e+12,4.0,1.000000,4.880000e+10
13319,Super built-up Area,Ready To Move,Doddathoguru,1,550.0,3.090909e+11,1.0,1.000000,1.700000e+09

In [63]:
df_2

,area_type,availability,location,BHK,total_sqft,price/sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2,1056.0,3.699811e+11,2.0,1.000000,3.907000e+09
1,Plot Area,Ready To Move,Chikka Tirupathi,4,2600.0,4.615385e+11,5.0,3.000000,1.200000e+10
2,Built-up Area,Ready To Move,Uttarahalli,3,1440.0,4.305556e+11,2.0,3.000000,6.200000e+09
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3,1521.0,6.245891e+11,3.0,1.000000,9.500000e+09
4,Super built-up Area,Ready To Move,Kothanur,2,1200.0,4.250000e+11,2.0,1.000000,5.100000e+09
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5,3453.0,6.689835e+11,4.0,0.000000,2.310000e+10
13316,Super built-up Area,Ready To Move,Richards Town,4,3600.0,1.111111e+12,5.0,1.584376,4.000000e+10
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2,1141.0,5.258545e+11,2.0,1.000000,6.000000e+09
13318,Super built-up Area,18-Jun,Padmanabhanagar,4,4689.0,1.040734e+12,4.0,1.000000,4.880000e+10
13319,Super built-up Area,Ready To Move,Doddathoguru,1,550.0,3.090909e+11,1.0,1.000000,1.700000e+09